name: Push image to ECR

on: 
    workflow_call: 
        inputs:
            image_tag:
                description: 'Tag for the image'
                required: true
                default: 'latest'
                type: string
            ecr_registry:
                description: 'ECR registry ID'
                required: true
                type: string    
            ecr_repo:
                description: 'ECR repository name'
                required: true
                type: string
            aws_region:
                description: 'AWS region'
                required: true
                default: 'eu-north-1'
                type: string
        secrets:
            AWS_ROLE_ARN:
                description: 'The ARN of the role to assume'
                required: true

jobs:
    push-to-ecr:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: ${{ inputs.aws_region }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2

            - name: Build, tag, and push docker image to Amazon ECR
              env:
                REGISTRY: ${{ inputs.ecr_registry }}
                REPOSITORY: ${{ inputs.ecr_repo }}
                IMAGE_TAG: ${{ inputs.image_tag }}
              run: |
                docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
                docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG


