name: Release

on:
  workflow_call:
    inputs:
    # Removed commit-id input, always releases from develop
      type:
        description: 'The type of release (e.g., patch, minor, major)'
        required: false
        type: string
        default: 'patch'
    secrets:
        GH_ACTION_PAT:
            description: 'GitHub Personal Access Token with repo permissions'
            required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  
          token: ${{ secrets.GH_ACTION_PAT }}
          ref: develop
            
      - name: Validate release type
        run: |
          if [[ "${{ inputs.type }}" != "patch" && "${{ inputs.type }}" != "minor" && "${{ inputs.type }}" != "major" ]]; then
            echo "Invalid release type: ${{ inputs.type }}. Must be one of: patch, minor, major."
            exit 1
          fi
      - name: Ensure branch is develop
        run: |
          if [[ "${GITHUB_REF##*/}" != "develop" ]]; then
            echo "This workflow can only be run from the develop branch."
            exit 1
          fi

      - name: Set git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Get current version
        id: get_version
        run: |
          CURRENT_VERSION=$(grep '"version":' package.json | sed -E 's/.*"([0-9]+\.[0-9]+\.[0-9]+(-SNAPSHOT)?)".*/\1/')
          echo "current_version=$CURRENT_VERSION" >> $GITHUB_OUTPUT
      
      - name: Get next version
        id: next_version
        uses: mchtugr/get-release-version@v1
        with:
          current_version: ${{ steps.get_version.outputs.current_version }}
          release_type: ${{ inputs.type }}
           

      - name: Bump version (release)
        id: version
        env:
          NEXT_VERSION: ${{ steps.next_version.outputs.next_version }}
        run: |
          RELEASE_VERSION=$(npm version $NEXT_VERSION --no-git-tag-version)
          echo "release_version=$RELEASE_VERSION" >> $GITHUB_OUTPUT

      - name: Commit and push release version to develop
        env:
          RELEASE_VERSION: ${{ steps.version.outputs.release_version }}
        run: |
          git add package.json package-lock.json || true
          git commit -m "chore(release): $RELEASE_VERSION"
          git push origin develop

      - name: Merge release to main
        run: |
          git fetch origin main
          git checkout main
          git merge -v origin/develop
          git push origin main

      - name: Tag and create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.release_version }}
          name: ${{ steps.version.outputs.release_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Get snapshot version
        id: snapshot_version
        uses: mchtugr/get-release-version@v1
        with:
          current_version: ${{ steps.version.outputs.release_version }}
          release_type: patch
          generate_snapshot: true

      - name: Switch back to develop and set snapshot version
        env: 
          SNAPSHOT_VERSION: ${{ steps.snapshot_version.outputs.next_version }}
        run: |
          git checkout develop
          npm version $SNAPSHOT_VERSION --no-git-tag-version
          git add package.json package-lock.json || true
          git commit -m "chore(release-candidate): v$SNAPSHOT_VERSION"
          git push origin develop
