name: Test Release Workflow

on: 
    workflow_dispatch: 
        inputs:
            type:
                description: 'The type of release'
                required: true
                type: choice
                options:
                    - patch
                    - minor
                    - major
            dry-run:
                description: 'DRY RUN - If true, the workflow will simulate the release process without making any changes'
                required: false
                type: boolean
                default: true        
jobs: 
  test-release:
    name: Call release workflow
    uses: mchtugr/shared-actions/.github/workflows/release.yaml@develop
    permissions:
      contents: write 
    with:
      type: ${{ inputs.type }}
      source-branch: 'develop'
      target-branch: 'main'
      dry-run: ${{ inputs.dry-run }}
    secrets:
      GH_ACTION_PAT: ${{ secrets.GH_ACTION_PAT }}  
